# Continuous integration for Gradle and JVM applications
image: gradle:jdk16

variables:
  # Using a fresh runtime for each build to isolate each runtime from any previous builds.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  # Variable for the runner at ENSICAEN
  http_proxy: http://193.49.200.22:3128
  https_proxy: http://193.49.200.22:3128
  HTTP_PROXY: http://193.49.200.22:3128
  HTTPS_PROXY: http://193.49.200.22:3128

before_script:
  - chmod +x gradlew
  - mv gradle.properties.ci gradle.properties

stages:
  - build
  - test

build:
  tags :
    - gitlab-runner-ensicaen
  stage: build
  script:
    - ./gradlew -Pci --console=plain --build-cache assemble
  only:
    - master

unit_test:
  tags :
    - gitlab-runner-ensicaen
  stage: test
  coverage: '/Coverage Total: ([0-9]{1,3})%/'
  only:
    - master
  script:
    - ./gradlew -Pci --console=plain test jacocoTestReport
    - cat build/jacocoHtml/index.html | grep -o 'Total[^%]*%' | sed 's/<.*>/ /; s/Total/Coverage Total:/'
